# Generated by Django 5.2.11 on 2026-03-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
